---

apiVersion: v1
kind: Service
metadata:
  name: gitea-postgresql-service
  namespace: gitea-app
spec:
  selector:
    app: gitea-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: gitea-app
spec:
  selector:
    app: gitea
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32500
  type: LoadBalancer
  externalIPs: 
    - 192.168.59.100