apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgresql-deployment
  namespace: gitea-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-postgresql
  template:
    metadata:
      labels:
        app: gitea-postgresql
    spec:
      containers:
        - name: gitea-postgresql
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: gitea
            - name: POSTGRES_USER
              value: gitea
            - name: POSTGRES_PASSWORD
              value: gitea
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  namespace: gitea-app
spec:
  replicas: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea:latest
          imagePullPolicy: Never
          livenessProbe:
            tcpSocket:
              port: 3000
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: gitea-data
              mountPath: /home/git/app/data
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: gitea-data-pvc