apiVersion: v1
kind: Namespace
metadata:
  name: gitea-app

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins 
      initContainers:
      - name: init-jenkins
        image:  jenkins:jcasc
        command: ['sh', '-c', 'cp -a /var/jenkins_home/* /mnt/pv-content/']
        volumeMounts:
         - name: jenkins-jobs-data
           mountPath: "/mnt/pv-content"
      containers:
        - name: jenkins
          image: jenkins:jcasc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-jobs-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-jobs-data
          persistentVolumeClaim:
            claimName: jenkins-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32600
      name: jenkins-port
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: jenkins-agent-port
  type: LoadBalancer
  externalIPs: 
    - 192.168.49.2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: permissive-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubelet
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-gitea-app-role
  namespace: gitea-app
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "services", "pvc"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-gitea-app-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-gitea-app-role
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default
