apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins:jcasc
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-jobs-data
              mountPath: /var/jenkins_home/jobs
      volumes:
        - name: jenkins-jobs-data
          persistentVolumeClaim:
            claimName: jenkins-data-pvc
 
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32600
  type: LoadBalancer
  externalIPs: 
    - 192.168.49.2

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: permissive-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubelet
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 